### Get message
// @no-log
GET http://localhost:8080/api/hello/SnapStart HTTP/1.1
Accept: application/json



### Bad Request
// @no-log
GET http://localhost:8080/api/exception/illegal-argument HTTP/1.1
Accept: application/json



### Get users (Requires authentication)
// @no-log
GET http://localhost:8080/api/users HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=



###
// @no-log
GET https://y3jrpavq7h.execute-api.eu-west-1.amazonaws.com/api/hello/Lambda HTTP/1.1
